BUILD_VERSION := 1.0.0
BUILD_DATE := $(shell date +%Y-%m-%d)
BUILD_COMMIT := $(shell git rev-parse HEAD)


.PHONY: run migrateup migratedown

run:
	go run cmd/shortener/main.go

migrateup: run
	"host=localhost port=5432 user=postgres password=nbvpass dbname=postgres sslmode=disable"

debug:
	dlv
	
build:
	go build -ldflags "-X main.buildVersion=$(BUILD_VERSION) -X main.buildDate=$(BUILD_DATE) -X main.buildCommit=$(BUILD_COMMIT)" -o shortener cmd/shortener/main.go