name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.4'  # Укажите версию Go, которую вы используете

      - name: Install dependencies
        run: go mod download

      - name: Install goveralls
        run: go get github.com/mattn/goveralls

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Calculate total coverage
        id: coverage
        run: |
          go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%'

      - name: Display total coverage
        run: echo "Total test coverage: ${{ steps.coverage.outputs.result }}%"

      - name: Calculate backend coverage
        # Предположим, что у вас есть отдельная метрика для полной базы бекенда.
        run: |
          # Замените `full_backend_coverage` на ваш способ получения процента покрытия бекенда.
          full_backend_coverage=80  # Пример: 80% общего покрытия бекенда
          total_coverage=${{ steps.coverage.outputs.result }}
          echo "Total coverage compared to full backend: $((total_coverage * 100 / full_backend_coverage))%"

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: bash <(curl -s https://coveralls.io/bash) || echo "Coveralls upload failed!"
